const fs = require('fs')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


global.SESSION_ID = process.env.SESSION_ID || 'IMMU-MD:~eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoidUVYTXBIbFp6UEljOWpMQUZ2VHM4VzNMRDB2Q0hyaFRUNUM0V2FZOWpWWT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoib21QVkd2WGREUW5oeklTcUlDYy9FVHp4Mm43KzZrQmxxSFdaYmc0R2YxND0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJDRDFzc2dsRHlkdXcrZklnTmpvRFlNRjErZ1VYTkk4ZjFQRHU5VFRNRDNrPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJnMVdKY0lVbms5c2xJdUxha3I2cE1yQ1ZUTUtwYStsNXd1MU5KUTlUZmw4PSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjRGeThlYXM1MVNUN1IxL05Qa2p0TXdDUkhqdnVoa251bXFzN09OdWxzMms9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Ik1WckF5SFJ2V0kzUXlLT3FUQTNIL0owZEt0QjJ3TXh0bFRqRVFvU044eEU9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiWVBvOXk0c3lWVGRXR3U4UnpOV3JtTXJWdW00TElCTDlYWmNRWXdBdkQwWT0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiNXdiQmhUdEF1REVadDJqNHdmUWUzcUNIc09RNkczSTIrWVFHWkQ5RDdtYz0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjRwTWU4dnY1UXlNRjhaSjZmOHNCTy82UFQ2QmxiVkhTeUhZR2F4WDB2WjdibGpXL2pVNnlkdFIwWnovUU5vcjZRVFJZNGFCT0sxOUkyaEJuQW5xQ2pBPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MTIwLCJhZHZTZWNyZXRLZXkiOiJyTzBPVkdZaEwwbkpUV0NXbURYcG9zbmI4MU1YWTRKQVFDSHRZd3FIdVhnPSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W3sia2V5Ijp7InJlbW90ZUppZCI6Ijk5NDQwMjc3OTcwNUBzLndoYXRzYXBwLm5ldCIsImZyb21NZSI6dHJ1ZSwiaWQiOiIzNUNGRUYwMUY5NERGM0FGOThBNkU5MTBCRjYzOTU3MSJ9LCJtZXNzYWdlVGltZXN0YW1wIjoxNzUyNzQ1OTY3fSx7ImtleSI6eyJyZW1vdGVKaWQiOiI5OTQ0MDI3Nzk3MDVAcy53aGF0c2FwcC5uZXQiLCJmcm9tTWUiOnRydWUsImlkIjoiOUE1QzE1NDBCQTcwREE4OUFDNThCREQzQjZBNDgyQzAifSwibWVzc2FnZVRpbWVzdGFtcCI6MTc1Mjc0NTk2N30seyJrZXkiOnsicmVtb3RlSmlkIjoiOTk0NDAyNzc5NzA1QHMud2hhdHNhcHAubmV0IiwiZnJvbU1lIjp0cnVlLCJpZCI6IjNFNjhGQ0U5RDA4MDQwRjNERTRBNDNDQ0YxMEIzREJCIn0sIm1lc3NhZ2VUaW1lc3RhbXAiOjE3NTI3NDU5Njl9XSwibmV4dFByZUtleUlkIjozMSwiZmlyc3RVbnVwbG9hZGVkUHJlS2V5SWQiOjMxLCJhY2NvdW50U3luY0NvdW50ZXIiOjEsImFjY291bnRTZXR0aW5ncyI6eyJ1bmFyY2hpdmVDaGF0cyI6ZmFsc2V9LCJyZWdpc3RlcmVkIjp0cnVlLCJwYWlyaW5nQ29kZSI6IjNHTENKOFBaIiwibWUiOnsiaWQiOiI5OTQ0MDI3Nzk3MDU6N0BzLndoYXRzYXBwLm5ldCIsImxpZCI6Ijc4NTM0MTMxMzU1NzUxOjdAbGlkIiwibmFtZSI6IkhhY2tlciDwn5iIIn0sImFjY291bnQiOnsiZGV0YWlscyI6IkNNWDh1YjRGRU9LUDQ4TUdHQUlnQUNnQSIsImFjY291bnRTaWduYXR1cmVLZXkiOiIwRG1IRjJpN1hIc2MzQkhEdW1URW1uNC94SkVJdVg2d2MxSlQvU29xYTBrPSIsImFjY291bnRTaWduYXR1cmUiOiJmODF5M3JWM0djQktBanFaaEx2VytwdDZUeFlqUGIxVTExTnlGbjVlcWdtT0VmSVdGT0E0c0Y0Vjh2WXU3U0lEUmcrcVNKVEw3QXJhSnB1SVBBbEZDZz09IiwiZGV2aWNlU2lnbmF0dXJlIjoiY2xKR29aTnFueXJLR2dNWWE4UUZkWlA1KzZSVTBvR3k1NVhPcDVLUEtLY2hyMkhvSG1WcnRFdW1CaVV6ckNQempLd2dkVHowUTZ3RFVJa1pvTUFIaUE9PSJ9LCJzaWduYWxJZGVudGl0aWVzIjpbeyJpZGVudGlmaWVyIjp7Im5hbWUiOiI5OTQ0MDI3Nzk3MDU6N0BzLndoYXRzYXBwLm5ldCIsImRldmljZUlkIjowfSwiaWRlbnRpZmllcktleSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IkJkQTVoeGRvdTF4N0hOd1J3N3BreEpwK1A4U1JDTGwrc0hOU1UvMHFLbXRKIn19XSwicGxhdGZvcm0iOiJhbmRyb2lkIiwicm91dGluZ0luZm8iOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJDQTBJQWc9PSJ9LCJsYXN0QWNjb3VudFN5bmNUaW1lc3RhbXAiOjE3NTI3NDU5NjUsImxhc3RQcm9wSGFzaCI6IjNSOVozOSIsIm15QXBwU3RhdGVLZXlJZCI6IkFBQUFBRTBWIn0='


global.PREFIX = process.env.PREFIXZ || '.'


global.mode = process.env.MODE || 'public';
// Set 'private' to enable private mode
// Set 'public' to enable public mode


global.botname = process.env.BOT_NAME || 'IMMU MD'

global.ownernumber = process.env.OWNER_NUMBER || '+994402779705'


global.antidelete = process.env.ANTIDELETE || 'private'
// options:- 'private', 'chat' or 'off'
// private = Sends to message yourself 
// chat = sends to the current chat 
// off = Disables detection of deleted messages


global.statusemoji = process.env.STATUS_EMOJI || "🧡,💚,🔥,✨,❤️,🥰,😎";


global.autoviewstatus = process.env.AUTO_STATUS_VIEW || 'false'


global.autoreactstatus = process.env.AUTO_STATUS_REACT || 'false'


global.timezones = process.env.TIMEZONE || "Pakistan/Karachi" 

let file = require.resolve(__filename)
fs.watchFile(file, () => {
  fs.unwatchFile(file)
  console.log(`Updated '${__filename}'`)
  delete require.cache[file]
  require(file)
})
